---
services:
  copilot-cli:
    container_name: copilot-cli
    image: dceoy/copilot-cli:latest
    build:
      context: .
      dockerfile: Dockerfile
      target: cli
      args:
        USER_NAME: agent
        USER_UID: '1001'
        USER_GID: '1001'
    environment:
      GITHUB_TOKEN: ${GITHUB_TOKEN:-}
    tty: true
    stdin_open: true
    volumes:
      - .:/workspace
      - copilot-data:/home/agent/.copilot
      - config-data:/home/agent/.config
    working_dir: /workspace
    post_start:
      - command: bash -c '[[ "$(stat -c "%U:%G" /home/agent/.copilot)" != "root:root" ]] || chown agent:agent /home/agent/.copilot'
        user: root
      - command: bash -c '[[ "$(stat -c "%U:%G" /home/agent/.config)" != "root:root" ]] || chown agent:agent /home/agent/.config'
        user: root
    entrypoint:
      - /usr/bin/zsh
    command:
      - -lc
      - 'copilot --yolo'
volumes:
  copilot-data:
  config-data:
